version: '3'
services:
  hotnow-token-platform:
    image: hotnow-token-platform
    build: .
    container_name: hotnow-token-platform
    working_dir: "/usr/src"
    command: "python -u token_platform/server.py"
    ports:
      - "8081:8081"
    volumes:
      - "./:/usr/src"
    environment:
      - PYTHONPATH=/usr/src/token_platform