version: '3'
services:
  hotnow-token-platform:
    image: hotnow-token-platform
    build: .
    container_name: hotnow-token-platform
    working_dir: "/usr/src"
    command: "python -u token_platform/server.py"
    ports:
      - "8081:8081"
    volumes:
      - "./:/usr/src"
    environment:
      - ASSET_CODE=HTKN
      - ISSUER=GDCNVJZCQ22253VL4ETJ36EDNZV7OXRVJOZ7474IWKSP5JZQSIWQ4CJK
      - HOST=localhost:8081
      - PYTHONPATH=/usr/src/token_platform
    networks:
      - hotnow-network
networks:
  hotnow-network:
    external:
      name: hotnow-network