version: '3'
services:
  hotnow-token-platform:
    image: hotnow-token-platform
    build: .
    container_name: hotnow-token-platform
    working_dir: "/usr/src"
    command: "python -u token_platform/server.py"
    ports:
      - "8081:8081"
    volumes:
      - "./:/usr/src"
    environment:
      - ASSET_CODE=HTKN
      - ISSUER=GDSB3JZDYKLYKWZ6NXDPPGPCYJ32ISMTZ2LVF5PYQGY4B4FGNIU2M5BJ
      - HOST=hotnow-token-platform
      - PYTHONPATH=/usr/src/token_platform
    networks:
      - hotnow-network
networks:
  hotnow-network:
    external:
      name: hotnow-network