version: '3'
services:
  hotnow-htkn-platform:
    image: "${REGISTRY:-hotnow-htkn-platform}:${TAG:-latest}"
    build: .
    container_name: hotnow-htkn-platform
    working_dir: "/usr/src"
    command: "python -u token_platform/server.py"
    ports:
      - "8081:80"
    volumes:
      - "./:/usr/src"
    environment:
      - ASSET_CODE=HTKN
      - ISSUER=GDSB3JZDYKLYKWZ6NXDPPGPCYJ32ISMTZ2LVF5PYQGY4B4FGNIU2M5BJ
      - PYTHONPATH=/usr/src/token_platform
      # - PASSPHRASE=Integration Test Network ; zulucrypto
      - PASSPHRASE=TESTNET
      # - HORIZON_URL=http://horizon-integrationnet:8000
      - HORIZON_URL=https://horizon-testnet.stellar.org
    networks:
      - hotnow-network
networks:
  hotnow-network:
    external:
      name: hotnow-network
